modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/KURONAMI333/sky-world/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
displayURL="https://github.com/KURONAMI333/sky-world"
logoFile="sky_world.png"
logoBlur=false
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="isekai_api"
    type="required"
    versionRange="[1.0.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="terralith"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="lithostitched"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="integrated_stronghold"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
